### PR TITLE
Challenge updates

### PR DESCRIPTION
**Pull request by aguynamedloren**
* Clarify copy for group pricing
* Add test case to isolate group pricing plus a single upcharge

### CODE REVIEW

**Comment by drewbaumann** [comment]
LGTM

**Comment by aguynamedloren** [comment]
Can you double check my math?  Don't wanna screw anyone over!

**Comment by drewbaumann** [comment]
@aguynamedloren Your math is sound.

**Comment by aguynamedloren** [comment]
Thanks!

**Pull request merged**
